"""update primary key of users

Revision ID: b990217612ff
Revises: adb6c2fc812e
Create Date: 2020-05-11 20:30:00.437786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b990217612ff'
down_revision = 'adb6c2fc812e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
